name: Node CI Demo

on:
  push:
    branches:
      - main

jobs:
  jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Run Linter
        run: npm run lint

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm test


#GitHub detects push
 #       ↓
#Creates temporary Linux computer
  #      ↓
#Downloads your repo
 #       ↓
#Installs Node.js
 #       ↓
#Runs npm install
 #       ↓
#Runs tests
 #       ↓
#Shows success/failure

   